---
title: "Ecology of Animal Societies - GitHub Landing Page"
subtitle: "Webpage with links to all things related to the EAS GitHub Account"
author: ""
date: "`r Sys.Date()`"
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: livingingroups/methods_support_repository
description: "Collection of links for the EAS department/MPI-AB"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```


```{r set_fold, include=FALSE}
source("R/initial_folding.R")
create_html_header("fold") # either "show" or "fold"
```

# Links

## Open Data Science (ODS) Wiki:
https://github.com/livingingroups/ods_wiki/wiki

## Methods Support Program:
https://livingingroups.github.io/methods_support_repository

## Resources and Tutorials:
https://github.com/livingingroups/resource_and_tutorials

## Template for EAS Bookdown (which is used for this page as well):
https://github.com/livingingroups/eas_bookdown